# For getting crop biomass data from original data

> Haolin Li
> May 16, 2024

## loading libs

```{r}
library(tidyverse)
library(tibble)
library(EML)
library(readr)
library(readxl)
library(dplyr)
```

## loading original dataset

```{r}
# set working directory as current directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()

# load data sheets
cap_path = "../cap_data/C_Data_2011-2015_0.xlsx"
cap_plot_entity = read_excel(cap_path, sheet = "Plot Identifiers") %>%
  as.data.frame() %>%
  slice(-1:-2)

cap_plot_agronomic = read_excel(cap_path, sheet = "Agronomic") %>%
  as.data.frame() %>%
  slice(-1:-2)
```

## creating the output table

```{r}
# cap_biomass = tibble(
#   Site = NA,
#   Year = NA,
#   Replicate = NA,
#   Plot = NA,
#   Tillage = 'TIL1',
#   Rotation = NA,
#   Species = NA,
#   Fraction = 'SEED',
#   # Biomass variables
#   Biomass_corn_vege = NA,
#   Biomass_corn_cob = NA,
#   Biomass_corn_grain = NA,
#   Biomass_soy_vege = NA,
#   Biomass_soy_grain = NA,
#   Biomass_cover_crop_fall = NA,
#   Biomass_cover_crop_spring = NA,
#   Biomass_cover_crop_weed_spring  = NA,
#   Biomass_red_clover_mixed_cover_fall = NA,
#   Biomass_weed_spring = NA
# )
```

## select and merge related columns

```{r}
cap_plot_agronomic_sub = cap_plot_agronomic %>%
  select(
    Site = uniqueid, 
    Year = year, 
    Plot = plotid, 
    Biomass_corn_vege = AGR04, # 'Corn vegetative biomass at R6 (dry)',
    Biomass_corn_cob = AGR32, # 'Corn cob biomass at R6 (dry)',
    Biomass_corn_grain = AGR33, # 'Corn grain biomass at R6 (dry)',
    Biomass_soy_vege = AGR05, # 'Soybean vegetative biomass at R8',
    Biomass_soy_grain = AGR34, # 'Soybean grain biomass at R8 (dry)',
    Biomass_cover_crop_fall = AGR06, # 'Cover crop (rye) biomass in late fall of previous year',
    Biomass_cover_crop_spring = AGR07, # 'Cover crop (rye) biomass at termination (spring)',
    Biomass_cover_crop_weed_spring = AGR39, # 'Cover crop (rye) and weedy biomass at termination (spring)',
    Biomass_red_clover_mixed_cover_fall = AGR41, # 'Red clover or mixed cover crop biomass in late fall of previous year',
    Biomass_weed_spring = AGR40, # 'Weedy biomass (only) at termination (spring)'
    )

cap_plot_entity_sub = cap_plot_entity %>%
  select(
    Site = uniqueid,
    Replicate = rep,
    Plot = plotid,
    Tillage = tillage,
    Rotation = rotation,
    Nitrogen = nitrogen
  )

# merge the selected table by Site and Plot
cap_biomass_merged = merge(cap_plot_agronomic_sub, cap_plot_entity_sub, by = c("Site", "Plot"))

# create the species column
for (i in 1:nrow(cap_biomass_merged)) {
  plot_site = cap_biomass_merged$Site[i]
  plot_id = cap_biomass_merged$Plot[i]
  plot_year = cap_biomass_merged$Year[i]
  year_column = paste(plot_year, 'crop', sep = '')
  plot_species = cap_plot_entity %>%
    filter(uniqueid == plot_site & plotid == plot_id) %>%
    select(year_column) %>%
    as.character()
  cap_biomass_merged$Species[i] = plot_species
}

# convert biomass columns to numeric
biomass_columns = c(
  "Biomass_corn_vege",
  "Biomass_corn_cob",
  "Biomass_corn_grain",
  "Biomass_soy_vege",
  "Biomass_soy_grain",
  "Biomass_cover_crop_fall",
  "Biomass_cover_crop_spring",
  "Biomass_cover_crop_weed_spring",
  "Biomass_red_clover_mixed_cover_fall",
  "Biomass_weed_spring"
)
# convert biomass columns to numeric
cap_biomass_merged[biomass_columns] = lapply(cap_biomass_merged[biomass_columns], as.numeric)
# replace NA with 0
cap_biomass_merged[biomass_columns] = lapply(cap_biomass_merged[biomass_columns], function(x) ifelse(is.na(x), 0, x))

```

## export the cover crop biomass csv

```{r}
# use Biomass_cover_crop_spring to represent cover crop biomass input
cap_biomass_covercrops = cap_biomass_merged %>%
  select(
    Year = Year,
    Replicate = Replicate,
    Rotation = Rotation,
    Nitrogen = Nitrogen,
    Tillage = Tillage,
    Species = Species,
    Biomass_kg_ha = Biomass_cover_crop_spring
  )

# export the cover crop biomass csv
write_csv(cap_biomass_covercrops, "cap_biomass_covercrops.csv")
```

## export the crop biomass csv

```{r}
# use all the related biomass combined to represent crop biomass input
cap_biomass_crops = cap_biomass_merged %>%
  mutate(total_biomass = Biomass_corn_vege + Biomass_corn_cob + Biomass_corn_grain + Biomass_soy_vege + Biomass_soy_grain) %>%
  select(
    Year = Year,
    Replicate = Replicate,
    Rotation = Rotation,
    Nitrogen = Nitrogen,
    Tillage = Tillage,
    Species = Species,
    Biomass_kg_ha = total_biomass
  )

# export the crop biomass csv
write_csv(cap_biomass_crops, "cap_biomass_crops.csv")
```

## export the weed biomass csv

```{r}
# use Biomass_weed_spring to represent weed biomass input
cap_biomass_weed = cap_biomass_merged %>%
  select(
    Year = Year,
    Replicate = Replicate,
    Rotation = Rotation,
    Nitrogen = Nitrogen,
    Tillage = Tillage,
    Species = Species,
    Biomass_kg_ha = Biomass_weed_spring
  )

# export the crop biomass csv
write_csv(cap_biomass_weed, "cap_biomass_weed.csv")
```

## we do not have information about compilation of the herbaceous biomass

```{r}
# skipped
```

